spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_education?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  flyway:
    encoding: UTF-8
    locations:
      - classpath:db/migration
  freemarker:
    template_exception_handler: rethrow
    enabled: true
    check-template-location: true
    cache: true  # enable in prod
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    expose-spring-macro-helpers: true
    settings:
      template_update_delay: 1h
      number_format: 0.##